# Generated by Django 5.1.7 on 2026-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcall',
            name='user',
        ),
        migrations.AddField(
            model_name='patientcall',
            name='room',
            field=models.CharField(default='', max_length=200),
        ),
    ]
